### ISSUE TITLE
Log changes to each dataset

### ISSUE THREAD

**Issue by ecoinvent** [OcelotProject/Ocelot#58]
In the dataset, there should be a "story" of what happened: identification of allocation method because of reason X; this product was flipped because Y, application of this allocation factor, scaled, etc.  This would make.  
Other option, a bit more ambitious: keep in the dataset copies of itself after each transformation.  The datasets might become a bit large, but there are not that many transformations.  Then the dataset would become its own documentation of what has been done, and it is not necessary to store multiple verseions of the database after different steps.

**Comment by ecoinvent** [comment]
Adapt also the dataset_to_excel function to output the changes, with the option to show or not the previous steps.

**Comment by cmutel** [comment]
This will require some substantial work, but should be done sooner rather than later.

Basically, we need a separate log at a [custom log level](http://stackoverflow.com/questions/2183233/how-to-add-a-custom-loglevel-to-pythons-logging-facility), and to capture this log output with a [separate handler](http://stackoverflow.com/questions/8162419/python-logging-specific-level-only). But this means that we need to add this separate logging to each function... and there are a lot of functions.

**Comment by cmutel** [comment]
Started work in `detailed-logging` branch. See also #105.

**Comment by cmutel** [comment]
Fixed in eeba15127b40ddde8bb8f0cf2a2678f0b22d2920. Still need to add the actual logging to most transformation processes.
